In [350]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [351]:
!rm bank*
!ls -la

total 464
drwxr-xr-x  10 vladflore  staff     320 Oct 10 23:44 .
drwxr-xr-x   6 vladflore  staff     192 Sep 16 18:03 ..
drwxr-xr-x  14 vladflore  staff     448 Oct 10 23:43 .git
-rw-r--r--   1 vladflore  staff      19 Sep 16 21:55 .gitignore
drwxr-xr-x   6 vladflore  staff     192 Oct 10 18:14 .ipynb_checkpoints
drwxr-xr-x   6 vladflore  staff     192 Oct  7 12:06 .mypy_cache
-rw-r--r--   1 vladflore  staff    5736 Sep 25 23:01 01-intro-hw.ipynb
-rw-r--r--   1 vladflore  staff  114677 Oct  8 11:37 02-regression-hw.ipynb
-rw-r--r--   1 vladflore  staff  106086 Oct 10 23:42 03-classification-hw.ipynb
-rw-r--r--   1 vladflore  staff      40 Sep 16 18:06 README.md

In [352]:
zip_url = 'https://archive.ics.uci.edu/static/public/222/bank+marketing.zip'
!wget $zip_url

--2024-10-10 23:44:07--  https://archive.ics.uci.edu/static/public/222/bank+marketing.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘bank+marketing.zip’

bank+marketing.zip      [       <=>          ] 999.85K   550KB/s    in 1.8s

2024-10-10 23:44:10 (550 KB/s) - ‘bank+marketing.zip’ saved [1023843]

In [353]:
!unzip bank+marketing.zip

Archive:  bank+marketing.zip
 extracting: bank.zip
 extracting: bank-additional.zip

In [354]:
!unzip bank.zip

Archive:  bank.zip
  inflating: bank-full.csv
  inflating: bank-names.txt
  inflating: bank.csv

In [355]:
data = 'bank-full.csv'
df = pd.read_csv(data, sep=';')
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [356]:
for col in df.columns.to_list():
    print(col)
    print()
    print(df[col].unique())
    print()

age

[58 44 33 47 35 28 42 43 41 29 53 57 51 45 60 56 32 25 40 39 52 46 36 49
 59 37 50 54 55 48 24 38 31 30 27 34 23 26 61 22 21 20 66 62 83 75 67 70
 65 68 64 69 72 71 19 76 85 63 90 82 73 74 78 80 94 79 77 86 95 81 18 89
 84 87 92 93 88]

job

['management' 'technician' 'entrepreneur' 'blue-collar' 'unknown'
 'retired' 'admin.' 'services' 'self-employed' 'unemployed' 'housemaid'
 'student']

marital

['married' 'single' 'divorced']

education

['tertiary' 'secondary' 'unknown' 'primary']

default

['no' 'yes']

balance

[ 2143    29     2 ...  8205 14204 16353]

housing

['yes' 'no']

loan

['no' 'yes']

contact

['unknown' 'cellular' 'telephone']

day

[ 5  6  7  8  9 12 13 14 15 16 19 20 21 23 26 27 28 29 30  2  3  4 11 17
 18 24 25  1 10 22 31]

month

['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']

duration

[ 261  151   76 ... 1298 1246 1556]

campaign

[ 1  2  3  5  4  6  7  8  9 10 11 12 13 19 14 24 16 32 18 22 15 17 25 21
 43 51 63 41 26 28 55 50 38 23 20 29 31 37 30 46 27 58 33 35 34 36 39 44]

pdays

[ -1 151 166  91  86 143 147  89 140 176 101 174 170 167 195 165 129 188
 196 172 118 119 104 171 117 164 132 131 123 159 186 111 115 116 173 178
 110 152  96 103 150 175 193 181 185 154 145 138 126 180 109 158 168  97
 182 127 130 194 125 105 102  26 179  28 183 155 112 120 137 124 187 190
 113 162 134 169 189   8 144 191 184 177   5  99 133  93  92  10 100 156
 198 106 153 146 128   7 121 160 107  90  27 197 136 139 122 157 149 135
  30 114  98 192 163  34  95 141  31 199  94 108  29 268 247 253 226 244
 239 245 204 231 238 258 230 254 265  71 223 246 250 266 240 205 261 259
 241 260 234 251 225 161 237 262 248 255 220 227 206 224 249 235 228 263
   2 270 232 252 207 200 269 233 256 273 272 242 264 208 214 222 271 203
 221 202 216 201 257 229 210 217  75 213  73  76 267 211 215  77 236  82
   6 209 274   1 243 212 275  80 276   9 279  12 280  88 277  85  84 219
  24  21 282  41 294  49 329 307 303 331 308 300  64 314 287 330 332 302
 323 318 333  60 326 335 313 312 305 325 327 336 309 328 322  39 316 292
 295 310 306 320 317 289  57 321 142 339 301 315 337 334 340 319  17  74
 148 341 299 344 342 324 345 346 304 281 343 338  14 347  15 291 348 349
 285 350 284  25 283 278  81   4  87  83  79  70  13 293  37  78  63  22
 296 355  66  19  35 360 357 354 351 362 358 365 298 286 364 363  47 361
 288 366 356 352 359 297 367 353 368  42 290  67 371 370 369  50  36 373
 374 372 311 375 378  59 379  40  18  43  20  69  38 385  56  55  44 391
  72 390  32  62 399 393  65 377 395 388 389 386  61 412 405 434 394 382
 459 440 397 383  68 461 462 463 422  51 457 430 442 403 454 428 392 410
 401 474 475 477 478  54 476 380 479  45  46 495  58  48 518  52 515 520
 511 536 387 218  33 544 435 436 555 433 446 558 469 616 561 553 384 592
 467 585 480 421 667 626 426 595 381 376 648 521 452 449 633 398  53 460
 670 551 414 557 687 404 651 686 425 504 578 674 416 586 411 756 450 745
 514 417 424 776 396 683 529 439 415 456 407 458 532 481 791 701 531 792
 413 445 535 784 419 455 491 431 542 470 472 717 437   3 782 728 828 524
 562 761 492 775 579 493 464 760 466 465 656 831 490 432 655 427 749 838
 769 587 778 854 779 850 771 594 842 589 603 484 489 486 409 444 680 808
 485 503 690 772 774 526 420 528 500 826 804 508 547 805 541 543 871 550
 530]

previous

[  0   3   1   4   2  11  16   6   5  10  12   7  18   9  21   8  14  15
  26  37  13  25  20  27  17  23  38  29  24  51 275  22  19  30  58  28
  32  40  55  35  41]

poutcome

['unknown' 'failure' 'other' 'success']

y

['no' 'yes']

In [357]:
features_string = """
age,
job,
marital,
education,
balance,
housing,
contact,
day,
month,
duration,
campaign,
pdays,
previous,
poutcome,
y
"""
features = [f.strip() for f in features_string.split(',')]

In [358]:
df.shape

(45211, 17)

In [359]:
df = df[features]
df.shape

(45211, 15)

In [360]:
df

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,2143,yes,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,29,yes,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,2,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,1506,yes,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,1,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,825,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,1729,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,5715,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,668,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,2971,no,cellular,17,nov,361,2,188,11,other,no

In [361]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [362]:
df.education.mode().values

array(['secondary'], dtype=object)

In [363]:
df.dtypes

age           int64
job          object
marital      object
education    object
balance       int64
housing      object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [364]:
df_for_corr = df.select_dtypes(include='int64')
df_for_corr

       age  balance  day  duration  campaign  pdays  previous
0       58     2143    5       261         1     -1         0
1       44       29    5       151         1     -1         0
2       33        2    5        76         1     -1         0
3       47     1506    5        92         1     -1         0
4       33        1    5       198         1     -1         0
...    ...      ...  ...       ...       ...    ...       ...
45206   51      825   17       977         3     -1         0
45207   71     1729   17       456         2     -1         0
45208   72     5715   17      1127         5    184         3
45209   57      668   17       508         4     -1         0
45210   37     2971   17       361         2    188        11

[45211 rows x 7 columns]

In [365]:
corr_matrix = df_for_corr.corr()
pairs = corr_matrix.unstack()
pairs = pairs[pairs < 1].abs().sort_values(ascending=False)
pairs.head(1).index

MultiIndex([('previous', 'pdays')],
           )

In [366]:
df.y = (df.y == 'yes').astype(int)
df

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,2143,yes,unknown,5,may,261,1,-1,0,unknown,0
1,44,technician,single,secondary,29,yes,unknown,5,may,151,1,-1,0,unknown,0
2,33,entrepreneur,married,secondary,2,yes,unknown,5,may,76,1,-1,0,unknown,0
3,47,blue-collar,married,unknown,1506,yes,unknown,5,may,92,1,-1,0,unknown,0
4,33,unknown,single,unknown,1,no,unknown,5,may,198,1,-1,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,825,no,cellular,17,nov,977,3,-1,0,unknown,1
45207,71,retired,divorced,primary,1729,no,cellular,17,nov,456,2,-1,0,unknown,1
45208,72,retired,married,secondary,5715,no,cellular,17,nov,1127,5,184,3,success,1
45209,57,blue-collar,married,secondary,668,no,telephone,17,nov,508,4,-1,0,unknown,0
45210,37,entrepreneur,married,secondary,2971,no,cellular,17,nov,361,2,188,11,other,0

In [367]:
from sklearn.model_selection import train_test_split
df_train, df_remaining = train_test_split(df, test_size=0.4, random_state=42)

df_val, df_test = train_test_split(df_remaining, test_size=0.5, random_state=42)

df.shape[0], df_train.shape[0] + df_val.shape[0] + df_test.shape[0]

(45211, 45211)

In [368]:
df_train = df_train.reset_index(drop=True)
df_train

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,45,entrepreneur,married,primary,-100,yes,unknown,27,may,240,6,-1,0,unknown,0
1,29,services,single,secondary,166,no,cellular,28,jul,108,8,-1,0,unknown,0
2,31,admin.,single,secondary,121,yes,unknown,20,may,187,1,-1,0,unknown,0
3,40,self-employed,single,tertiary,1693,yes,cellular,17,nov,353,1,-1,0,unknown,0
4,28,services,single,secondary,317,yes,unknown,16,may,21,3,-1,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27121,44,housemaid,single,primary,1059,no,unknown,18,jun,2093,1,-1,0,unknown,1
27122,23,student,single,tertiary,508,no,cellular,8,sep,210,1,92,1,failure,0
27123,34,technician,divorced,tertiary,1317,yes,cellular,15,may,239,1,-1,0,unknown,0
27124,33,retired,married,secondary,165,no,unknown,7,may,111,1,-1,0,unknown,0
27125,38,blue-collar,married,primary,-41,yes,cellular,21,jul,68,10,-1,0,unknown,0

In [369]:
df_val = df_val.reset_index(drop=True)
df_val

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,36,management,married,secondary,565,no,cellular,27,mar,300,1,-1,0,unknown,1
1,25,blue-collar,single,primary,-221,yes,unknown,23,may,250,1,-1,0,unknown,0
2,35,management,single,tertiary,1162,no,cellular,30,apr,175,1,-1,0,unknown,1
3,56,self-employed,married,tertiary,0,no,cellular,19,nov,122,1,-1,0,unknown,0
4,45,blue-collar,married,primary,101,yes,unknown,12,may,460,5,-1,0,unknown,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9037,22,technician,single,secondary,283,yes,cellular,22,mar,254,2,-1,0,unknown,1
9038,49,management,married,tertiary,391,no,unknown,17,jun,128,1,-1,0,unknown,0
9039,37,entrepreneur,married,secondary,3,no,cellular,20,nov,96,1,-1,0,unknown,0
9040,33,blue-collar,married,primary,217,yes,cellular,20,apr,198,1,339,3,failure,0
9041,46,management,divorced,tertiary,4917,yes,cellular,31,jul,5,2,-1,0,unknown,0

In [370]:
df_test = df_test.reset_index(drop=True)
df_test

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,29,blue-collar,married,secondary,2,yes,cellular,22,jul,96,1,-1,0,unknown,0
1,50,unknown,married,primary,341,yes,cellular,20,apr,670,4,340,2,success,1
2,34,management,single,tertiary,171,yes,cellular,7,may,191,1,294,1,failure,0
3,41,housemaid,married,tertiary,783,yes,unknown,30,may,130,2,-1,0,unknown,0
4,31,management,married,tertiary,557,yes,cellular,18,jul,111,1,-1,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9038,37,entrepreneur,married,tertiary,41,no,cellular,14,jul,388,3,-1,0,unknown,0
9039,35,technician,married,secondary,294,yes,cellular,9,mar,301,1,90,4,success,1
9040,38,admin.,married,secondary,0,yes,telephone,16,jul,264,5,-1,0,unknown,0
9041,43,entrepreneur,single,tertiary,0,yes,unknown,26,may,142,3,-1,0,unknown,0
9042,51,technician,married,tertiary,1347,yes,cellular,30,apr,116,1,79,2,success,0

In [371]:
y_train = df_train.y.values
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [372]:
y_val = df_val.y.values
y_val

array([1, 0, 1, ..., 0, 0, 0])

In [373]:
y_test = df_test.y.values
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [374]:
del df_train['y']
del df_val['y']
del df_test['y']

In [375]:
df_train

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome
0,45,entrepreneur,married,primary,-100,yes,unknown,27,may,240,6,-1,0,unknown
1,29,services,single,secondary,166,no,cellular,28,jul,108,8,-1,0,unknown
2,31,admin.,single,secondary,121,yes,unknown,20,may,187,1,-1,0,unknown
3,40,self-employed,single,tertiary,1693,yes,cellular,17,nov,353,1,-1,0,unknown
4,28,services,single,secondary,317,yes,unknown,16,may,21,3,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27121,44,housemaid,single,primary,1059,no,unknown,18,jun,2093,1,-1,0,unknown
27122,23,student,single,tertiary,508,no,cellular,8,sep,210,1,92,1,failure
27123,34,technician,divorced,tertiary,1317,yes,cellular,15,may,239,1,-1,0,unknown
27124,33,retired,married,secondary,165,no,unknown,7,may,111,1,-1,0,unknown
27125,38,blue-collar,married,primary,-41,yes,cellular,21,jul,68,10,-1,0,unknown

In [376]:
df_val

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome
0,36,management,married,secondary,565,no,cellular,27,mar,300,1,-1,0,unknown
1,25,blue-collar,single,primary,-221,yes,unknown,23,may,250,1,-1,0,unknown
2,35,management,single,tertiary,1162,no,cellular,30,apr,175,1,-1,0,unknown
3,56,self-employed,married,tertiary,0,no,cellular,19,nov,122,1,-1,0,unknown
4,45,blue-collar,married,primary,101,yes,unknown,12,may,460,5,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9037,22,technician,single,secondary,283,yes,cellular,22,mar,254,2,-1,0,unknown
9038,49,management,married,tertiary,391,no,unknown,17,jun,128,1,-1,0,unknown
9039,37,entrepreneur,married,secondary,3,no,cellular,20,nov,96,1,-1,0,unknown
9040,33,blue-collar,married,primary,217,yes,cellular,20,apr,198,1,339,3,failure
9041,46,management,divorced,tertiary,4917,yes,cellular,31,jul,5,2,-1,0,unknown

In [377]:
df_test

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome
0,29,blue-collar,married,secondary,2,yes,cellular,22,jul,96,1,-1,0,unknown
1,50,unknown,married,primary,341,yes,cellular,20,apr,670,4,340,2,success
2,34,management,single,tertiary,171,yes,cellular,7,may,191,1,294,1,failure
3,41,housemaid,married,tertiary,783,yes,unknown,30,may,130,2,-1,0,unknown
4,31,management,married,tertiary,557,yes,cellular,18,jul,111,1,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9038,37,entrepreneur,married,tertiary,41,no,cellular,14,jul,388,3,-1,0,unknown
9039,35,technician,married,secondary,294,yes,cellular,9,mar,301,1,90,4,success
9040,38,admin.,married,secondary,0,yes,telephone,16,jul,264,5,-1,0,unknown
9041,43,entrepreneur,single,tertiary,0,yes,unknown,26,may,142,3,-1,0,unknown
9042,51,technician,married,tertiary,1347,yes,cellular,30,apr,116,1,79,2,success

In [378]:
numerical_features = set(df_train.select_dtypes(include='int64').columns.to_list())
numerical_features

{'age', 'balance', 'campaign', 'day', 'duration', 'pdays', 'previous'}

In [379]:
categorical_features = set(df_train.columns.to_list()).difference(numerical_features)
categorical_features

{'contact', 'education', 'housing', 'job', 'marital', 'month', 'poutcome'}

In [380]:
assert len(numerical_features.intersection(categorical_features)) == 0
numerical_features = list(numerical_features)
categorical_features = list(categorical_features)

In [381]:
df_train[categorical_features].nunique()

contact       3
education     4
marital       3
month        12
poutcome      4
housing       2
job          12
dtype: int64

In [382]:
from sklearn.metrics import mutual_info_score

In [383]:
df_train_mi = df_train[categorical_features].apply(lambda s: mutual_info_score(s, y_train))
df_train_mi.sort_values(ascending=False).round(2).index[0]

'poutcome'